repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.11
  hooks:
    # Run the linter.
    - id: ruff-check
      exclude: ^notebooks/.*\.ipynb$

    # Run the formatter.
    - id: ruff-format
      exclude: ^notebooks/.*\.ipynb$

