minimum_pre_commit_version: "3.5.0"

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff (lint via uv)
        description: Run ruff check with fixes
        entry: uv run ruff check --force-exclude --fix --ignore E721,E741
        language: system
        types_or: [python, pyi]
        require_serial: true
        files: ^(src/|tests/|setup.py)
        exclude: ^notebooks/.*\.ipynb$

      - id: ruff-format
        name: ruff (format via uv)
        description: Run ruff format
        entry: uv run ruff format --force-exclude --line-length 100
        language: system
        types_or: [python, pyi]
        require_serial: true
        exclude: ^notebooks/.*\.ipynb$